### ISSUE TITLE
Python: Traceback

### ISSUE THREAD

**Issue by youthatninja** [nickberckley/bool_tool#11]
If you open the search menu(space/F3)  in 3dViewport with no obj selected

Python: Traceback (most recent call last):
  File "ppData\Roaming\Blender Foundation\Blender\4.2\extensions\blender_org\bool_tool\ui.py", line 169, in draw
    boolean_extras_menu(self, context)
  File "\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\blender_org\bool_tool\ui.py", line 53, in boolean_extras_menu
    if active_object.booleans.canvas == True and any(modifier.name.startswith("boolean_") for modifier in active_object.modifiers):
       ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'booleans'

**Comment by youthatninja** [comment]
And a lot of Tracebacks from Tissue addon

**Comment by nickberckley** [comment]
Thanks. Tissue issues are not related to this repository, but I'll fix the Bool Tool one

**Comment by nickberckley** [comment]
Fixed with 506f192
