### ISSUE TITLE
Add an option to not use boolean_cutters collection

### ISSUE THREAD

**Issue by Ataraxia-Mechanica** [nickberckley/bool_tool#12]
I prefer to organize boolean objects by myself and doesn't want them to be moved around.

**Comment by nickberckley** [comment]
Cutters aren't moved around, they keep all their collections which they already have (including scene collection), they're just linked to additional collection. 

You can still see those objects in outliner and interact with them as you like, put them in collection, whatever. Additional `boolean_cutters` collection doesn't prevent that.

Only thing that collection does is give quick way to select/delete all cutters in the scene with one click

**Comment by julius** [comment]
@Ataraxia-Mechanica Fixed addon: https://github.com/julius/bool_tool_nocollection/releases/tag/v1.1.1-nocollection

@nickberckley I manage my cutters so I can hide/unhide. The extra collection just gets in the way. I use your extension to add the modifiers more quickly, I do not want extra behaviour. Maybe you can make the collection an option, like what you did with the auto-parenting.

**Comment by nickberckley** [comment]
How do you manage your cutters differently than putting them in a collection?

**Comment by julius** [comment]
@nickberckley  Multiple collections. I use Blender for 3D Printing. Each part gets its own collection and an extra sub-collection for cutting objects.

**Comment by nickberckley** [comment]
I've included the optional to make collection optional and renameable. But I gotta say I use this for same purpose, for 3D printing, and problem you're describing shouldn't be affecting you. Objects in Blender can belong to multiple collections. When collections are enabled from preferences (as of next version) it simply adds objects to new collection, but keeps all collections they already have. So if you don't want, you can simply untick red collection in outliner and continue your work normally. You don't lose ability to put cutters in your own collections, they're in same place as they were before and can be interacted with normally. Collections feature is additive.
