### ISSUE TITLE
Problem with new Blender version

### ISSUE THREAD

**Issue by Adika660** [nickberckley/bool_tool#15]
I have installed the new version of Blender. I thought that all tools will stay the same. Problem came when I tried to use the bool tool. It did not work. Than I tried to turn it on. I searched for it, like it was in the instructions on net. It was not found. So I do not know what to do.

**Comment by nickberckley** [comment]
Do you enable online access in preferences? (In System > Network) category.
If you do that you can go to Get Extensions tab and search for Bool Tool and click install.

If you have enabled but still can't find the add-on file a bug report for Blender. This is not the particular add-on issue.
