### ISSUE TITLE
Click lag with v1.0

### ISSUE THREAD

**Issue by MissyX26** [nickberckley/bool_tool#18]
When v1.0 in installed, i have lag when clicking things (for example number of segments on the bevel modifier, even when there's no booleans in the scene at all). This does not happen with 0.4.1.

**Comment by nickberckley** [comment]
Hi. I'm not sure if Bool Tool is even capable of such thing. There is nothing in the code that can potentially be doing that.
Can you try disabling Bool Tool from Preferences > Add-ons tab in Blender 4.2, close, reopen Blender with same files and see if lag is still there?

You can also try disabling "Versioning" and "Experimenta" in add-on preferences if they're enabled and do the same.

**Comment by MissyX26** [comment]
The lag goes away as soon as i disable Bool Tool v1.0 in the addons tab (even without closing and opening Blender again but i just tested by closing Blender and opening again like you suggested but same thing). Versioning and Experimental are off already.

**Comment by nickberckley** [comment]
Does that happen in every scene? Even default one? If not, send me the file where it's happening.

Also, do you by any chance have other versions of Bool Tool installed in Add-ons tab? Multiple objects with same names can cause problems.

**Comment by MissyX26** [comment]
Yes it does happen on default scene and no, only 1 version of Bool Tool installed.

**Comment by nickberckley** [comment]
I'm sorry you're experiencing problems, but I can't do anything at this point. I have no information and this hasn't been reported before, so I can't generalize. In theory I don't think Bool Tool is capable of affecting performance when there are no booleans (if experimental is disabled). One last thing I would advise you to do is try disabling other add-ons you have one-by-one (while Bool Tool) is enabled to see if disabling any of them solves the problem, it can be that other add-on is conflicting with it. I have no other ideas.

**Comment by MissyX26** [comment]
I just tried it on Blender set to start up with factory defaults (no addons enabled at all) and enabled Bool Tool v1.0 and it happens again. Which makes it even weirder since it doesn't seem to happen to you from what you told me.

**Comment by nickberckley** [comment]
Well Bool Tool 1.0 is used by around 30k+ people and this hasn't been reported yet, so it is quite strange. How do you test if it lags or not? Where exactly do you experience it?

**Comment by MissyX26** [comment]
For example : i add a bevel modifier and then press the arrows to add segments .. click fast enough and you should see it happen. It doesn't register every click then and does just fine with 0.4.1.

**Comment by nickberckley** [comment]
Can you record a video of same task with and without Bool Tool enabled so I can get the idea?

**Comment by MissyX26** [comment]
Without : https://drive.google.com/file/d/1AVLcYsKMsb6NNqhmkMcR7Cp3KHvugDn-/view
With : https://drive.google.com/file/d/1AnhZxO58UlBuAQOSwQf8ZLydAjgIyAt3/view
I know it looks like i'm just clicking slower but i'm not.

**Comment by nickberckley** [comment]
Can you open console from Window > Toggle System Console after you're done clicking and copy if you see any error messages you think might be from Bool Tool? That is the last thing I can think of

**Comment by MissyX26** [comment]
No errors messages at all.

**Comment by nickberckley** [comment]
I'm afraid I can't be anymore help. I will close this thread now but I will keep thinking about the issue. If you'll see anything more concrete that might help us pinpoint the issue please comment here anytime.
