### ISSUE TITLE
Double click to select cutter works on the remove button

### ISSUE THREAD

**Issue by Ataraxia-Mechanica** [nickberckley/bool_tool#21]
![image](https://github.com/user-attachments/assets/bd7be0de-48bb-45e8-a113-f874d50729c2)
When there are at least 3 modifiers and clicking the remove button fast to remove multiple cutters, the second click selects the second cutter instead of deleting it.

**Comment by nickberckley** [comment]
I'm afraid this is a limitation. Its not possible to detect which button is under the cursor, as long as its in modifiers panel dbl-click selects. I'll make this feature optional.

P.S. I recommend never manually removing Bool Tool modifiers and use either "Remove Cutter" or "Remove All Cutters" operators. It will do clean-up as well, like remove unnecessary properties, enable objects for render, and etc. You can also use cutters list from Edit > Booleans to remove/apply cutters for active object.
