### ISSUE TITLE
Bug: Python error when trying to cut instances

### ISSUE THREAD

**Issue by mac4kent** [nickberckley/bool_tool#25]
See picture for Mac
![Boolean bug](https://github.com/user-attachments/assets/b5a4134f-92b6-408b-9fba-0450451901a1)

by Kent Davis

**Comment by nickberckley** [comment]
Error message will be improved for this, but in Blender you cant apply modifiers on linked instances. Every object has to have unique mesh data. Thats just how instancing works

**Comment by mac4kent** [comment]
Previous your add-ons bool tool it worked but latest version bool tool appear cause error code.
I do use Macintosh not for Windows and not for Linux.
Make sure focus for mac and you can found.

**Comment by mac4kent** [comment]
I send to you file .blend
https://mega.nz/file/9xtQASjB#9Y25PkeQGjrVtkGy86fehURxVq4su8L7n5wxMvmLITs

**Comment by nickberckley** [comment]
There is no bug. You can't do booleans on instances. Please learn more about general modeling and what instances are to avoid those mistakes. I'll handle the bad error message

**Comment by mac4kent** [comment]
allright
